### ISSUE TITLE
'ERR_UNHANDLED_REJECTION'

### ISSUE THREAD

**Issue by sakalsa** [Dexalot/samplebot#4]
![ss3](https://user-images.githubusercontent.com/17409677/201080607-760a0e1d-a5b7-4e53-8178-2c9930c665c4.png)

**Comment by sakalsa** [comment]
<img width="1286" alt="Ekran Resmi 2022-11-12 20 56 46" src="https://user-images.githubusercontent.com/17409677/201488070-b44112c8-09fe-43b3-b6a6-67f48312dea0.png">

Error is different now.
Unexpected token

**Comment by sakalsa** [comment]
It is a connection problem. My test vps on ovh dc  and its blocking connct to sexalot-test api. I fixed.

**Comment by cdincoglu** [comment]
Great thanks for resolving it on your own
